baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'anubis'

paginate = 10

[[menu.main]]
identifier = "archive"
name = "Archive"
title = "Archive"
url = "/posts/"
weight = 0

[params]
author = "Adam Parker"
email = "mail@example.org"
avatar = "/images/me.png"
description = "Time is an illusion, Lunch doubly so - Douglas Adams"
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "dark"
mainSections = [ "posts" ]
sectionsWithFullContentOnListPage = [ "notes" ]
readMore = false
readNextPosts = 5
disableSummary = true
toc = true
tocWordCount = 300
copyCodeButton = true
rssAsSocialIcon = true
mathjax = false
utterancesRepo = ""
utterancesTheme = ""
utterancesIssue = ""
utterancesLabel = ""
graphcommentId = ""

[params.isso]
enabled = true
data = "https://comments.example.com/"
jsLocation = "https://comments.example.com/js/embed.min.js"
css = true
lang = "de"
replyToSelf = true
requireAuthor = true
requireEmail = true
id = "thread-id"
avatar = true
avatar-bg = "#f0f0f0"
feed = false

[[params.social]]
id = "github"
name = "grab-a-byte"

[markup.goldmark.renderer]
unsafe = true
