baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'tailwind'

[params]
  # dir name of your blog content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  [params.header]
    logo = "logo.png"

  [params.footer]
    since = 2023
    poweredby = true

[menu]

  [[menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "/posts"
    weight = 0

 [taxonomies]
category = "categories"
tag = "tags"
series = "series"

[[params.social_media.items]]
enabled = true
title = 'Github'
icon = 'brand-github'
link = 'https://github.com/grab-a-byte/'